config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"
  resources :users, only: [:new, :create, :show] do
    resources :goals, only: [:new, :index]
  end
  resource :session, only: [:new, :create, :destroy]
  resources :goals, except: [:new, :index]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true

  belongs_to :author, class_name: User
end

app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable
  end
  
end

app/models/goal.rb
class Goal < ActiveRecord::Base

  validates :name, :user, presence: true
  validates :completed, :public_goal, inclusion: [true, false]

  after_initialize :default_completed

  belongs_to :user

  include Commentable

  def default_completed
    self.completed ||= false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  has_many :goals

  has_many :authored_comments, class_name: Comment, foreign_key: :author_id

  include Commentable

  after_initialize :ensure_session_token

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = self.find_by(username: username)

    return nil unless user

    if user.is_password?(password)
      user
    else
      nil
    end
  end

  def set_session_token
    self.session_token = SecureRandom.urlsafe_base64
    save!
    session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login(user)
    user.set_session_token
    session[:session_token] = user.session_token
  end

  def logout
    current_user.set_session_token
    session[:session_token] = nil
  end

  def require_user
    redirect_to new_session_url if !logged_in?
  end

  def require_guest
    redirect_to root_url if logged_in?
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :require_owner, only: [:edit, :update, :destroy]

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user
    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def index
    @user = User.find(params[:user_id])
    @goals = @user.goals

    if params[:completed] == 'false'
      @goals = @goals.where(completed: false)
    elsif params[:completed] == 'true'
      @goals = @goals.where(completed: true)
    end

    if current_user != @user
      @goals = @goals.where(public_goal: true)
    end
  end

  def show
    @goal = Goal.find(params[:id])

    if current_user != @goal.user
      redirect_to user_goals_url(@goal.user) unless @goal.public_goal
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to user_goals_url(@goal.user)
  end

  private
  def goal_params
    the_params = params.require(:goal).permit(:name, :user_id, :public_goal, :completed)
    the_params[:public_goal] = (the_params[:public_goal] == "true")
    the_params[:completed] = !!the_params[:completed]
    the_params
  end

  def require_owner
    @goal = Goal.find(params[:id])
    redirect_to user_goals_url(@goal.user) unless current_user = @goal.user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(
      user_params[:username],
      user_params[:password]
    )

    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = ["Invalid login!"]
      @user = User.new(user_params)
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:password, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<form action="<%= goal_url(@goal) %>" method="post">
  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="hidden"
    name="_method"
    value="patch">

  <label for="name">Name: </lable>
  <input type="text"
    id="name"
    name="goal[name]"
    value="<%= @goal.name %>">
  <br />

  Public? :<br/>
  <input type="radio"
    id="public_goal_true"
    name="goal[public_goal]"
    value="true">
  <label for="public_goal_true">True</lable>
  <br/>

  <input type="radio"
    id="public_goal_false"
    name="goal[public_goal]"
    value="false">
  <label for="public_goal_false">False</lable>
  <br/>

  <br/>
  <input type="checkbox"
    id="completed"
    name="goal[completed]"
    value="true">
  <label for="completed">Completed?</lable>
  <br/>

  <input type="submit" value="Update Goal">
</form>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<form action="<%= goals_url %>" method="post">
  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="name">Name: </lable>
  <input type="text"
    id="name"
    name="goal[name]"
    value="<%= @goal.name %>">
  <br />

  Public? :<br/>
  <input type="radio"
    id="public_goal_true"
    name="goal[public_goal]"
    value="true">
  <label for="public_goal_true">True</lable>
  <br/>

  <input type="radio"
    id="public_goal_false"
    name="goal[public_goal]"
    value="false">
  <label for="public_goal_false">False</lable>
  <br/>

  <input type="submit" value="Create Goal">
</form>

app/views/goals/show.html.erb
<%= @goal.name %>
<%= link_to "Back to Index", user_goals_url(@goal.user) %>
<%= button_to "Delete Goal", goal_url(@goal), method: :delete %>

app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/errors" %>

<% if logged_in? %>
  <%= current_user.username %>
  <%= button_to "Sign Out", session_url, method: :delete %>
<% else %>
  <%= link_to "Sign In", new_session_url %>
  <%= link_to "Sign Up", new_user_url %>
<% end %>

<%= yield %>

</body>
</html>

app/views/shared/_list_comments.html.erb
<% if comments %>
  <ul>
    <% comments.each do |comment| %>
      <li> <%= comment.body %> - says <%= comment.author.username %> </li>
    <% end %>
  </ul>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="username">Username: </lable>
  <input type="text"
    id="username"
    name="user[username]"
    value="<%= @user.username %>">

  <label for="password">Password: </lable>
  <input type="password"
    id="password"
    name="user[password]">

  <input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<%= @user.username %>

<%= render "shared/list_comments", comments: @user.comments %>